### ISSUE TITLE
Sync README and code with current steps to set up a minimal CloudBrowser dev environment

### ISSUE THREAD

**Issue by matthewlmcclure** [brianmcd/cloudbrowser#44]
I'm trying to get CloudBrowser minimally running on CentOS 6.4. It isn't obvious what the relevant steps are, so I'm discovering them by trial and error.

**Comment by ashimaathri** [comment]
59074c2e5f25753d266b38ea4d53004cd84b21cf fixes this.

**Comment by matthewlmcclure** [comment]
Thanks, @ashimaathri. I'll give the new instructions a shot.
